name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      TS3_HOST: ${{ secrets.TS3_HOST }}
      TS3_PASSWORD: ${{ secrets.TS3_PASSWORD }}
      TS3_NICKNAME: ${{ secrets.TS3_NICKNAME }}
      TS3_USERNAME: ${{ secrets.TS3_USERNAME }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 'latest'

      - name: Install dependencies
        run: bun install

      - name: Type check
        run: bun run typecheck

      - name: Lint
        run: bun run lint

      - name: Build
        run: bun run build
